/*
 * Copyright (c) 2026, Barcelona Supercomputing Center
 * Contact: mess             [at] bsc [dot] es
 *          victor.xirau     [at] bsc [dot] es
 *          petar.radojkovic [at] bsc [dot] es
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *     * Neither the name of the copyright holder nor the names
 *       of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "arch/riscv/RiscvAssembler.h"
#include <algorithm>

namespace {

bool isRvvMode(ISAMode mode) {
    return mode == ISAMode::RVV1_0 || mode == ISAMode::RVV0_7;
}

int resolvedRvvBytesPerMemOp(const KernelConfig& config) {
    if (config.resolved_bytes_per_mem_op > 0) {
        return config.resolved_bytes_per_mem_op;
    }
    return isRvvMode(config.isa_mode) ? 32 : 8;
}

}

std::string RiscvAssembler::generateLoad(int offset, int reg) const {
    std::ostringstream oss;
    if (isRvvMode(config_.isa_mode)) {
        int step = resolvedRvvBytesPerMemOp(config_);
        oss << "        \"vle64.v v" << reg << ", (x20);\\n\"\n"
            << "        \"addi x20, x20, " << step << ";\\n\"\n";
    } else {
        if (offset >= -2048 && offset < 2048) {
            oss << "        \"ld x19, " << offset << "(x20);\\n\"\n";
        } else {
            oss << "        \"li x30, " << offset << ";\\n\"\n"
                << "        \"add x30, x20, x30;\\n\"\n"
                << "        \"ld x19, 0(x30);\\n\"\n";
        }
    }
    return oss.str();
}

std::string RiscvAssembler::generateStore(int offset, int reg) const {
    std::ostringstream oss;
    if (isRvvMode(config_.isa_mode)) {
        int step = resolvedRvvBytesPerMemOp(config_);
        oss << "        \"vse64.v v" << reg << ", (x23);\\n\"\n"
            << "        \"addi x23, x23, " << step << ";\\n\"\n";
    } else {
        if (offset >= -2048 && offset < 2048) {
            oss << "        \"sd x24, " << offset << "(x23);\\n\"\n";
        } else {
            oss << "        \"li x30, " << offset << ";\\n\"\n"
                << "        \"add x30, x23, x30;\\n\"\n"
                << "        \"sd x24, 0(x30);\\n\"\n";
        }
    }
    return oss.str();
}

std::string RiscvAssembler::generateLoopControl(int increment, int labelId) const {
    std::ostringstream oss;
    oss << "\n";
    if (increment > 0 && increment < 2048) {
        oss << "        \"addi x18, x18, " << increment << ";\\n\"\n";
    } else {
        oss << "        \"li x30, " << increment << ";\\n\"\n"
            << "        \"add x18, x18, x30;\\n\"\n";
    }
    oss << "        \"add x20, %0, x18;\\n\"\n"
        << "        \"add x23, %4, x18;\\n\"\n"
        << "        \"blt x18, %2, ..L_" << labelId << ";\\n\"\n";
    return oss.str();
}

std::string RiscvAssembler::generatePause() const {
    return "        \"mv x21, ra;\\n\"\n"
           "        \"jal ra, nop_;\\n\"\n"
           "        \"mv ra, x21;\\n\"\n";
}

std::string RiscvAssembler::generateHeader() const {
    std::ostringstream oss;
    oss << "/*\n"
        << " * Generated by Mess Kernel Generator (RISC-V)\n"
        << " * Mode: MultiSequential access\n"
        << " */\n\n"
        << "#include <stdio.h>\n"
        << "#include <stdint.h>\n"
        << "#include <unistd.h>\n"
        << "#include \"utils.h\"\n\n"
        << "void print_usage(char *argv[], char* usage)\n"
        << "{\n"
        << "    fprintf(stderr,\"Usage: %s %s\", argv[0], usage);\n"
        << "}\n\n";
    return oss.str();
}

std::string RiscvAssembler::generateRegisterSetup() const {
    return "    register ssize_t i;\n"
           "    i = 0;\n"
           "    uint64_t tmp = 8*(*array_size);\n\n";
}

std::string RiscvAssembler::generateVectorRegisterInit() const {
    if (isRvvMode(config_.isa_mode)) {
        return "      \"vsetvli x0, x0, e64, m1, ta, ma;\\n\"\n"
               "      \"add x20, %0, x18;\\n\"\n"
               "      \"add x23, %4, x18;\\n\"\n";
    }
    return "\n"
           "      \"add x20, %0, x18;\\n\"\n"
           "      \"add x23, %4, x18;\\n\"\n";
}

std::string RiscvAssembler::generateFooter() const { return ""; }

std::string RiscvAssembler::generateAsmStart() const {
    return "    asm __volatile__ (\n"
           "      \"mv x18, x0;\\n\"\n"
           "      \"mv x22, %3;\\n\"\n"
           "      \"mv x24, x0;\\n\"";
}

std::string RiscvAssembler::generateAsmEnd() const {
    return "      :\n"
           "      : \"r\" (a_array), \"r\" (i), \"r\" (tmp), \"r\" (*pause), \"r\" (b_array)\n"
           "      : \"x18\", \"x19\", \"x20\", \"x21\", \"x22\", \"x23\", \"x24\", \"x30\", \"memory\"\n"
           "    );\n";
}

std::string RiscvAssembler::getPointerChaseLoopAsm() const {
    return "            \"addi %2, %2, -1;\"\n"
           "            \"bnez %2, start_loop_%%=;\"";
}

std::string RiscvAssembler::getPointerChaseInstruction() const {
    return "        \"add x21, %2, %1; ld %1, 0(x21);\"";
}

std::string RiscvAssembler::generatePointerChaseBurstLoop() const {
    return R"(
        register uint64_t i = BURST_ITERS;
        register struct line *start = array;
        register uint64_t next = current_offset;

        __asm__ __volatile__ (
            "li x20, 1;"
            "start_loop_%=:"
            #include "loop.h"
            "sub %0, %0, x20;"
            "bgt %0, x0, start_loop_%=;"
            : "+r" (i), "+r" (next)
            : "r" (start)
            : "x20", "x21", "memory"
        );

        current_offset = next;
)";
}

std::string RiscvAssembler::generateNopFile() const {
    return R"(#include <stdlib.h>
#include <stdio.h>

void volatile nop_(void) {
    asm __volatile__ (
        "bne x22, x0, start_pause;\n"
        "j end;\n"
        "start_pause:"
        "mv x23, x22;\n"
        "start_loop:\n"
        "nop;\n"
        "addi x23, x23, -1;\n"
        "bne x23, x0, start_loop;\n"
        "end:"
        :
        :
        : "x30", "x4", "x10", "x23"
    );
}

int nop(int *ntimes) {
    return 0;
}
)";
}

